### ISSUE TITLE
How to generate snp_matrix

### ISSUE THREAD

**Issue by OlenaMaiakovska** [MinzhuXie/H-PoPG#3]
I will repeat the same question which was not covered in previous issue, from @habibr
i am interested on using your program but stumbled upon how the SNP matrix file generated. Is there any scripts or program to produce that?

**Comment by sinamajidian** [comment]
I also wanted to you use this program. But some issues in input format hindered me. I'm looking forward to hear response from authors for your question and their idea for my workaround. It may not be perfect but is a step forward.

Using bi-allelic assumption, one idea is to use ExtractHairs from HapCUT
https://github.com/vibansal/hapcut
But it's only for diploid. A workaround is to artificially convert polyploids to diploid only input of Extracthairs.  For a triploid, to convert 0/0/1 and 0/1/1 into 0/1 you may use bash lines
```
sed  "s/0\/0\/1/0\/1/;s/0\/1\/1/0\/1/" var.vcf  > edited.vcf
extractHAIRS --mbq 1 --mmq 1  --bam read.bam --VCF out.vcf > frag.txt
```
Second idea (a bit slow) is use part of the code from   
https://github.com/EhsanMotazedi/TriPoly
```
Frag_lsts, Qual_lsts, SampleNames = bamprocess.get_frags(args[0], args[1], maxIS, mbq, mmq)
```
in which you may need bamprocess.py,  genotypes.py, reads.py files from that and also a bit coding in python to write the output in a text file.

**Comment by OlenaMaiakovska** [comment]
Seems like this can be helpful :
ExtractHAIRS from HapCUT to generate the fragment matrix from VCF file:
https://git.wageningenur.nl/motaz001/Haplosim/blob/master/FragmentPoly.py from Haplosim(haplosim.py) pipeline

**Comment by OlenaMaiakovska** [comment]
@smajidian, do you think after the conversion to biallelic frag file it will be still possible to use it for haplotype identification with H-PoPG for polyploid (my case is triploid biallelic organism, AA'B)?

**Comment by sinamajidian** [comment]
@OlenaMaiakovska  Yes. That idea (converting polyploids to diploid artificially in VCF file) works for haplotyping of polyploids. I'm also working on a package for that. 

Consider you have a sorted aligned bam file (reads_sorted.bam) and a set of called variants (vars.vcf) of a triploid. I suggest you two options:

**First.** 
Install (hapcut)[https://github.com/vibansal/hapcut] and then run the following in bash
```
sed  "s/0\/0\/1/0\/1/;s/0\/1\/1/0\/1/" vars.vcf  > vars_edited.vcf
extractHAIRS --mbq 1 --mmq 1  --bam reads_sorted.bam --VCF vars_edited.vcf > frag.txt
java -jar H-PoPG.jar -p 3 -f frag.txt -o phased_haplotypes.txt 
```

**Second.**
Install [extract_poly](https://github.com/smajidian/extract_poly). Then run

```
cat vars.vcf | grep -v "1/1/1" | grep -v "0/0/0" | grep -v "mnp" > vars_filtered.vcf
../build/extractHAIRS  --bam reads_sorted.bam --VCF vars_filtered.vcf --out fragment_file
java -jar H-PoPG.jar -p 3 -f fragment_file -o phased_haplotypes.txt 
```

**Comment by OlenaMaiakovska** [comment]
Dear @smajidian,
thank you very much, it was helpful, I receive the phased haplotypes in blocks.

**Comment by OlenaMaiakovska** [comment]
Maybe it is not related to this topic anymore but after the generation of phased haplotype blocks how to assign them back to the vcf file, or how I can generate the sequences of haplotypes from the phased file?

**Comment by MinzhuXie** [comment]
The major allele at a SNP locus is coded as 0, and the alternative allele is coded as 1. Since we have gotten  the phased 01 sequence, the ACGT sequence of a haplotype could be obtained by replacing 0 with the major allele and 1 with the alternative allele. The ACGT sequence at other loci than the SNPs could be obtained from the reference genome sequence.

**Comment by OlenaMaiakovska** [comment]
@MinzhuXie Thank you for your reply! 
 I was asking how the SNP positions from phased haplotypes.txt file correspond to actual SNP positions from vcf file?  Or how I can proceed phased_haplotypes.txt file further? I am not really sure about positions (first column) in phased_haplotypes.txt file

**Comment by MinzhuXie** [comment]
Please see the new version H-PoPGv0.2.0.jar, which could output the detailed information about SNP positions, DNA bases of haplotypes with option "-d filename"
