### ISSUE TITLE
How to write phased genotypes back to vcf file

### ISSUE THREAD

**Issue by OlenaMaiakovska** [MinzhuXie/H-PoPG#4]
After obtaining phased file I need to get consensus fasta sequence for each haplotype and I suppose I can do it through conversation of generated phased file information back to genotype information in vcf file according to SNP positions. How it can be done? Any suggestions?

**Comment by MinzhuXie** [comment]
Please see the new version H-PoPGv0.2.0.jar, which could output the detailed information about SNP positions, DNA bases of haplotypes with option "-d filename"
