### ISSUE TITLE
Unable to access jarfile

### ISSUE THREAD

**Issue by OlenaMaiakovska** [MinzhuXie/H-PoPG#5]
Seems like PolyPlotyping.jar file is missing..

**Comment by MinzhuXie** [comment]
java -jar H-PoPGv0.2.0.jar -b thefilename.bam -v thefilename.vcf -p n_ploid -o outputfile.txt -d outputACGT.txt

**Comment by OlenaMaiakovska** [comment]
I was wondering how to access PolyPlotyping.jar file in order to create Frag file? 

In your readme protocol: 
 3) Only transfer a BAM File to a Frag file (the read covering less than 2 SNPs are discarded):

java -jar PolyPlotyping.jar -v[cf] vcffilename -b[am] bamfilenme -o outputFragFilename -b2f

**Comment by MinzhuXie** [comment]
Sorry for the typo.  PolyPlotyping.jar should be H-PoPGv0.2.0.jar
